services:
  linter:
    build:
      context: .
      dockerfile: ./Docker/node/dockerfile
    container_name: linter
    working_dir: /work
    volumes:
      - .:/work
      - /work/node_modules
    tty: true
    command: npm run lint

  pdf:
    image: t4t5u0/lualatex:1
    container_name: pdf
    working_dir: /work
    volumes:
      - ./writing_space/:/work
    tty: true
    command: latexmk

  clean:
    image: t4t5u0/lualatex:1
    container_name: clean
    working_dir: /work
    volumes:
      - ./writing_space/:/work
    tty: true
    command: latexmk -c